Build JetTower with authorizeUrl api
Byzanteam/jet-tower-plugin-js pull request #1
Opened 2024-03-08 07:30 UTC by CptBreeza

2024-03-08 09:38 UTC, fahchen requested changes
这个按我们讨论的结果再调整下哇

2024-03-14 07:58 UTC, fahchen commented on src/types.ts
> +  updated_at: string;
这个地方的 key 我们能不能都转成 camel 形式的？

2024-03-15 02:43 UTC, fahchen commented on src/types.ts
> +  data: Record<string, UserInfoValue>;
这里是不是不用限制呀？

```suggestion
  data: Record<string, unkonwn>;
```

2024-03-15 02:43 UTC, fahchen commented on src/types.ts
> +  updatedAt: number;
这个给一下注释呢
```suggestion
  // The updatedAt is a number representing the number of seconds from 1970-01-01T00:00:00Z as measured in UTC until the date/time.
  updatedAt: number;
```

2024-03-15 05:14 UTC, CptBreeza commented on src/types.ts
> +  data: Record<string, UserInfoValue>;
这个为啥是 unknown 呢？

2024-03-15 07:14 UTC, fahchen approved these changes

2024-03-15 07:38 UTC, merged